semester:
  current:
    year: 2024/2025
    winter_semester:
      start_date: '2024-10-01'
      end_date: '2025-02-28'
    summer_semester:
      start_date: '2025-03-01'
      end_date: '2025-09-30'
  previous:
    year: 2023/2024
    winter_semester:
      start_date: '2023-10-01'
      end_date: '2024-02-28'
    summer_semester:
      start_date: '2024-03-01'
      end_date: '2024-09-30'
